### ISSUE TITLE
Empty line on --dict option generates exception

### ISSUE THREAD

**Issue by RafaelAPB** [sylvainhalle/textidote#128]
When a newline is in the dictionary used as input of the option --dict, an exception is raised:

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 0, end 1, length 0
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3720)
	at java.base/java.lang.String.substring(String.java:1909)
	at org.languagetool.rules.spelling.SpellingCheckRule.lambda$updateIgnoredWordDictionary$0(SpellingCheckRule.java:217)
	at java.base/java.util.stream.Collectors.lambda$groupingBy$53(Collectors.java:1127)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1605)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.languagetool.rules.spelling.SpellingCheckRule.updateIgnoredWordDictionary(SpellingCheckRule.java:217)
	at org.languagetool.rules.spelling.SpellingCheckRule.addIgnoreTokens(SpellingCheckRule.java:209)
	at ca.uqac.lif.textidote.rules.CheckLanguage.<init>(CheckLanguage.java:95)
	at ca.uqac.lif.textidote.Main.mainLoop(Main.java:590)
	at ca.uqac.lif.textidote.Main.mainLoop(Main.java:126)
	at ca.uqac.lif.textidote.Main.main(Main.java:112)

A solution would be emitting a warning instead of the exception

**Comment by sylvainhalle** [comment]
Or maybe just ignore the line? What do you prefer?

**Comment by RafaelAPB** [comment]
@sylvainhalle I think that for the end user ignoring the line should be fine.
