### ISSUE TITLE
Exception when running on a .tex

### ISSUE THREAD

**Issue by jcelerier** [sylvainhalle/textidote#23]
```
$ java -jar ~/textidote.jar --read-all --check en main.tex
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
TeXtidote v0.4 - A linter for LaTeX documents
(C) 2018 Sylvain Hallé - All rights reserved

Exception in thread "main" java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at ca.uqac.lif.textidote.rules.CheckSubsections.evaluate(CheckSubsections.java:97)
	at ca.uqac.lif.textidote.Linter.evaluateAll(Linter.java:126)
	at ca.uqac.lif.textidote.Main.mainLoop(Main.java:318)
	at ca.uqac.lif.textidote.Main.main(Main.java:93)
```

A simple repro : 
```TeX
\documentclass{article}
\begin{document}
\section{A}
\chapter{B}
\end{document}
```

Another: 

```TeX
\documentclass{article}
\begin{document}
\section{A}
\paragraph{B}
\end{document}
```

**Comment by sylvainhalle** [comment]
I can reproduce the error with the first file, but it runs without error for the second file with release 0.4. The problem is corrected with my upcoming commit on the `dev` branch.

**Comment by sylvainhalle** [comment]
Still fails with:
```
\begin{document}
\paragraph{foo}
\part{bar}
\chapter{baz}
```
