### ISSUE TITLE
Error on specifying --check language

### ISSUE THREAD

**Issue by philastrophist** [sylvainhalle/textidote#27]
I get an error when I use the `--check` argument 

It happens not matter what I specify (`en`, or `en_UK` etc)

```
TeXtidote v0.5.1 - A linter for LaTeX documents
(C) 2018 Sylvain Hallé - All rights reserved

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/languagetool/JLanguageTool : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:616)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:56)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:303)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
	at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:316)
	at ca.uqac.lif.textidote.Main.mainLoop(Main.java:313)
	at ca.uqac.lif.textidote.Main.main(Main.java:96)
```

**Comment by sylvainhalle** [comment]
Hi! What version of Java do you have? TeXtidote requires Java 8 or greater 
to work.

--
Sylvain Hallé, Ph.D.
Professeur titulaire / Full professor
Titulaire de la Chaire de recherche du Canada en spécification,
test et vérification de systèmes informatiques
Canada Research Chair on Software Specification, Testing and Verification
Université du Québec à Chicoutimi, Canada
E-mail: shalle@acm.org
Web: http://leduotang.ca/sylvain

**Comment by philastrophist** [comment]
ah yes. got it, thanks
