### ISSUE TITLE
Problem processing German texts

### ISSUE THREAD

**Issue by christiankral** [sylvainhalle/textidote#38]
I just discovered your tool through a link on researchgate.net and I do like it a lot. Great work!

I installed version 0.5.1 and tried to run a sample file 
```
textidote --html --check de sample.tex >sample.html
``` 

In this case I get the following error message:
```
TeXtidote v0.5.1 - A linter for LaTeX documents
(C) 2018 Sylvain Hallé - All rights reserved

Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.languagetool.language.German.getRelevantRules(German.java:168)
	at org.languagetool.language.GermanyGerman.getRelevantRules(GermanyGerman.java:43)
	at org.languagetool.JLanguageTool.getAllBuiltinRules(JLanguageTool.java:279)
	at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:186)
	at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:157)
	at org.languagetool.MultiThreadedJLanguageTool.<init>(MultiThreadedJLanguageTool.java:76)
	at org.languagetool.MultiThreadedJLanguageTool.<init>(MultiThreadedJLanguageTool.java:67)
	at org.languagetool.MultiThreadedJLanguageTool.<init>(MultiThreadedJLanguageTool.java:51)
	at ca.uqac.lif.textidote.rules.CheckLanguage.<init>(CheckLanguage.java:85)
	at ca.uqac.lif.textidote.Main.mainLoop(Main.java:313)
	at ca.uqac.lif.textidote.Main.main(Main.java:96)
Caused by: java.lang.IllegalArgumentException: 'de' is not a language code known to LanguageTool. Supported language codes are: ast-ES, be-BY, br-FR, ca-ES, ca-ES-valencia, da-DK, el-GR, en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA, eo, es, fa, fr, gl-ES, it, ja-JP, nl, pl-PL, pt, pt-BR, pt-PT, ro-RO, ru-RU, sk-SK, sl-SI, sr, sv, uk-UA, zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See http://wiki.languagetool.org/java-api for details.
	at org.languagetool.Languages.getLanguageForShortCode(Languages.java:151)
	at org.languagetool.rules.de.OldSpellingData.<init>(OldSpellingData.java:49)
	at org.languagetool.rules.de.OldSpellingRule.<clinit>(OldSpellingRule.java:35)
	... 11 more
```

I also tried the country codes `de_AT` and `de_CH` as specified on https://github.com/sylvainhalle/textidote, but they did not work either.

textidote works good with English tex files and language specification, i.e., `--check en`. So there are no error messages triggered when English texts are processed.

**Comment by sylvainhalle** [comment]
This is a problem caused by the LanguageTool JAR file that comes with TeXtidote. I'll try to create a new JAR file and see if that solves the problem.

**Comment by sylvainhalle** [comment]
The problem was exactly what I thought. The next release of TeXtidote will used a fixed version of the LanguageTool JAR bundle that will solve this problem.

**Comment by ashwinvis** [comment]
Regression?

```sh
❯ textidote --check en paper1/article.tex
TeXtidote v0.8 - A linter for LaTeX documents and others
(C) 2018-2019 Sylvain Hallé - All rights reserved

Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.languagetool.language.English.getRelevantRules(English.java:201)
	at org.languagetool.language.AmericanEnglish.getRelevantRules(AmericanEnglish.java:51)
	at org.languagetool.JLanguageTool.getAllBuiltinRules(JLanguageTool.java:390)
	at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:276)
	at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:305)
	at org.languagetool.MultiThreadedJLanguageTool.<init>(MultiThreadedJLanguageTool.java:86)
	at org.languagetool.MultiThreadedJLanguageTool.<init>(MultiThreadedJLanguageTool.java:67)
	at org.languagetool.MultiThreadedJLanguageTool.<init>(MultiThreadedJLanguageTool.java:51)
	at ca.uqac.lif.textidote.rules.CheckLanguage.<init>(CheckLanguage.java:86)
	at ca.uqac.lif.textidote.Main.mainLoop(Main.java:584)
	at ca.uqac.lif.textidote.Main.mainLoop(Main.java:126)
	at ca.uqac.lif.textidote.Main.main(Main.java:112)
Caused by: java.lang.IllegalArgumentException: 'en' is not a language code known to LanguageTool. Supported language codes are: zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See http://wiki.languagetool.org/java-api for details.
	at org.languagetool.Languages.getLanguageForShortCode(Languages.java:237)
	at org.languagetool.Languages.getLanguageForShortCode(Languages.java:214)
	at org.languagetool.rules.en.EnglishDashRule.<clinit>(EnglishDashRule.java:37)
	... 12 more
```
