### ISSUE TITLE
StringIndexOutOfBoundsException when dictionary contains names including '

### ISSUE THREAD

**Issue by obonaventure** [sylvainhalle/textidote#40]
Hello,

When a dictionary includes names such as CONF'12 that correspond to acronyms of scientific conferences for example, textidote raises exceptions

textidote -read-all --check en_UK --dict d.txt t.txt
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_UK.UTF-8)
TeXtidote v0.5.1 - A linter for LaTeX documents
(C) 2018 Sylvain Hall? - All rights reserved

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 0, end 1, length 0
	at java.lang.String.checkBoundsBeginEnd(java.base@9-internal/String.java:3119)
	at java.lang.String.substring(java.base@9-internal/String.java:1907)
	at org.languagetool.rules.spelling.SpellingCheckRule.lambda$updateIgnoredWordDictionary$0(SpellingCheckRule.java:108)
	at java.util.stream.Collectors.lambda$groupingBy$49(java.base@9-internal/Collectors.java:1049)
	at java.util.stream.ReduceOps$3ReducingSink.accept(java.base@9-internal/ReduceOps.java:169)
	at java.util.HashMap$KeySpliterator.forEachRemaining(java.base@9-internal/HashMap.java:1600)
	at java.util.stream.AbstractPipeline.copyInto(java.base@9-internal/AbstractPipeline.java:484)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(java.base@9-internal/AbstractPipeline.java:474)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(java.base@9-internal/ReduceOps.java:913)
	at java.util.stream.AbstractPipeline.evaluate(java.base@9-internal/AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(java.base@9-internal/ReferencePipeline.java:511)
	at org.languagetool.rules.spelling.SpellingCheckRule.updateIgnoredWordDictionary(SpellingCheckRule.java:108)
	at org.languagetool.rules.spelling.SpellingCheckRule.addIgnoreTokens(SpellingCheckRule.java:100)
	at ca.uqac.lif.textidote.rules.CheckLanguage.<init>(CheckLanguage.java:94)
	at ca.uqac.lif.textidote.Main.mainLoop(Main.java:313)
	at ca.uqac.lif.textidote.Main.main(Main.java:96)

Simple text file 👍 
simple test CONF'11 etc.

Simple dictionnary

CONF'11
CONF
abcde

**Comment by sylvainhalle** [comment]
I cannot reproduce this bug with the info I have. Here are the files I used:

Contents of `text.tex`: 

```
\begin{document}
Hello world, and CONF'11 too.
\end{document}
```

Contents of `dict.txt`:

```
CONF'11
CONF
abcde
```

Command used:

    textidote --check en --dict dict.txt text.tex

I get:

```
Found 0 warning(s)
Total analysis time: 3 seconds

Everything is OK!
```

Could you please send me the exact files that cause the error?

**Comment by obonaventure** [comment]
I tried to reproduce it again and it failed. I'll come back to you if it see the problem again with a simple example
