### ISSUE TITLE
n-grams analysis (using `--languagemodel`) gives `java.util.ServiceConfigurationError`

### ISSUE THREAD

**Issue by sim590** [sylvainhalle/textidote#59]
When running the following command (file read from `stdin`):

```sh
textidote --languagemodel /path/containing/fr/directory --html --dict .ltignore --check fr
```

I end up with the following error:

```
Using N-grams from /home/simon/Téléchargements
TeXtidote v0.7 - A linter for LaTeX documents and others
(C) 2018-2019 Sylvain Hallé - All rights reserved

Exception in thread "main" java.util.ServiceConfigurationError: Cannot instantiate SPI class: org.apache.lucene.codecs.lucene50.Lucene50Codec
	at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:82)
	at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:51)
	at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:38)
	at org.apache.lucene.codecs.Codec$Holder.<clinit>(Codec.java:47)
	at org.apache.lucene.codecs.Codec.forName(Codec.java:113)
	at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:469)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:361)
	at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:53)
	at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:50)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:731)
	at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:50)
	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:63)
	at org.languagetool.languagemodel.LuceneSingleIndexLanguageModel$LuceneSearcher.<init>(LuceneSingleIndexLanguageModel.java:242)
	at org.languagetool.languagemodel.LuceneSingleIndexLanguageModel$LuceneSearcher.<init>(LuceneSingleIndexLanguageModel.java:230)
	at org.languagetool.languagemodel.LuceneSingleIndexLanguageModel.getCachedLuceneSearcher(LuceneSingleIndexLanguageModel.java:183)
	at org.languagetool.languagemodel.LuceneSingleIndexLanguageModel.addIndex(LuceneSingleIndexLanguageModel.java:119)
	at org.languagetool.languagemodel.LuceneSingleIndexLanguageModel.<init>(LuceneSingleIndexLanguageModel.java:93)
	at org.languagetool.languagemodel.LuceneLanguageModel.<init>(LuceneLanguageModel.java:65)
	at org.languagetool.language.French.getLanguageModel(French.java:132)
	at org.languagetool.JLanguageTool.activateLanguageModelRules(JLanguageTool.java:341)
	at ca.uqac.lif.textidote.rules.CheckLanguage.activateLanguageModelRules(CheckLanguage.java:241)
	at ca.uqac.lif.textidote.Main.mainLoop(Main.java:546)
	at ca.uqac.lif.textidote.Main.mainLoop(Main.java:124)
	at ca.uqac.lif.textidote.Main.main(Main.java:110)
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'Lucene50' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene40, Lucene41]
	at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:114)
	at org.apache.lucene.codecs.PostingsFormat.forName(PostingsFormat.java:112)
	at org.apache.lucene.codecs.lucene50.Lucene50Codec.<init>(Lucene50Codec.java:155)
	at org.apache.lucene.codecs.lucene50.Lucene50Codec.<init>(Lucene50Codec.java:75)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:72)
	... 23 more
```

The n-grams files were downloaded from the following URL:

https://languagetool.org/download/ngram-data/

as instructed by the [LanguageTool documentation page][ltpage].

[ltpage]: http://wiki.languagetool.org/finding-errors-using-n-gram-data

**Comment by sylvainhalle** [comment]
Something needs to be edited inside the JAR file; solution here: https://anwaarlabs.wordpress.com/2017/02/25/lucene-an-spi-class-of-type-org-apache-lucene-codecs-codec-with-name-does-not-exist/

I can patch the existing release, but I'll have to think of a way to automate this for future releases.

**Comment by sylvainhalle** [comment]
Release v0.7.1 should fix the problem. Feel free to reopen if the problem persists.

**Comment by sim590** [comment]
I just tested 0.7.1. It worked fine! Thanks for the quick reaction!

**Comment by inventionate** [comment]
Thank you for the great program. Unfortunately I get exactly this error when I want to use the latest version (0.8.3) with current n-gram data. Is there a solution for this?

**Comment by sylvainhalle** [comment]
The new LanguageTool jar seems to have the exact same issue as the previous one. I'll reopen and try to fix it again.

**Comment by Jollywatt** [comment]
I’m getting this exact error, but don’t fix it, even after following the instructions at https://anwaarlabs.wordpress.com/2017/02/25/lucene-an-spi-class-of-type-org-apache-lucene-codecs-codec-with-name-does-not-exist/.

Is there a workaround simple enough for non-Java users?

**Comment by bong0** [comment]
I "patched" the 0.8.3 version manually and it works for me. Use at your own risk. I edited it those three files in META_INF using vim.

https://transfer.sh/64Oy0T/textidote_patched.jar

**Comment by sylvainhalle** [comment]
@bong0 Thanks for your contribution. I would like to integrate your changes in the pipline that creates the [LanguageTool fat JAR](https://github.com/sylvainhalle/languagetool-bundle/). Could you please tell me which files you modified and what changes you made to them?

**Comment by bong0** [comment]
sure, hope that helps:
3 files changed
[changed] META-INF/services/org.apache.lucene.codecs.PostingsFormat  

```
❯ diff t1/**/META-INF/services/org.apache.lucene.codecs.PostingsFormat  t2/**/META-INF/services/org.apache.lucene.codecs.PostingsFormat
17a18
> org.apache.lucene.codecs.lucene50.Lucene50PostingsFormat
```

[changed] META-INF/services/org.apache.lucene.codecs.DocValuesFormat  
```
❯ diff t1/**/META-INF/services/org.apache.lucene.codecs.DocValuesFormat  t2/**/META-INF/services/org.apache.lucene.codecs.DocValuesFormat
20a21
> org.apache.lucene.codecs.lucene54.Lucene54DocValuesFormat
```

[changed] META-INF/services/org.apache.lucene.codecs.Codec 

```
❯ diff t1/**/META-INF/services/org.apache.lucene.codecs.Codec  t2/**/META-INF/services/org.apache.lucene.codecs.Codec           
24a25
> org.apache.lucene.codecs.lucene54.Lucene54Codec
```

**Comment by WrichikBasu** [comment]
Adding the lines mentioned in the [above post by `bong0`](https://github.com/sylvainhalle/textidote/issues/59#issuecomment-1499581419) didn't work for me. Had to comment out some of the existing lines to make it work.

The contents of those files that worked for me are as follows:

`META-INF/services/org.apache.lucene.codecs.PostingsFormat` :
```
org.apache.lucene.codecs.lucene41.Lucene41PostingsFormat
org.apache.lucene.codecs.lucene50.Lucene50PostingsFormat
# org.apache.lucene.codecs.lucene54.Lucene54PostingsFormat
```

`META-INF/services/org.apache.lucene.codecs.DocValuesFormat` :
```
# org.apache.lucene.codecs.lucene42.Lucene42DocValuesFormat
# org.apache.lucene.codecs.lucene45.Lucene45DocValuesFormat
org.apache.lucene.codecs.lucene49.Lucene49DocValuesFormat
org.apache.lucene.codecs.lucene410.Lucene410DocValuesFormat
org.apache.lucene.codecs.lucene50.Lucene50DocValuesFormat
org.apache.lucene.codecs.lucene54.Lucene54DocValuesFormat
```

`META-INF/services/org.apache.lucene.codecs.Codec` :
```
# org.apache.lucene.codecs.lucene40.Lucene40Codec
org.apache.lucene.codecs.lucene41.Lucene41Codec
# org.apache.lucene.codecs.lucene42.Lucene42Codec
# org.apache.lucene.codecs.lucene45.Lucene45Codec
# org.apache.lucene.codecs.lucene46.Lucene46Codec
org.apache.lucene.codecs.lucene49.Lucene49Codec
org.apache.lucene.codecs.lucene410.Lucene410Codec
org.apache.lucene.codecs.lucene50.Lucene50Codec
# org.apache.lucene.codecs.lucene53.Lucene53Codec
org.apache.lucene.codecs.lucene54.Lucene54Codec
```

Not sure if the Java version matters, but I am using OpenJDK v22.0.2.

**Comment by NuclearPowerNerd** [comment]
I am using TeXtidote `0.8.2` with `ngrams-en-20150817.zip` and I am getting the same error as above. I have essentially no knowledge of Java which I assume is needed to interpret the original link given or to modify the lines in files in other responses (for example its not clear to me what or where this `META_INF` directory is, is that part of the source and I have to rebuild after editing it? Or?).

Any help here would be appreciated.

**Comment by juliankessel** [comment]
Hey @NuclearPowerNerd the META_INF directory and the listings are within a .jar file. A jar is basically  a .zip and can be unpacked using a zip tool/extractor. 7zip should do e.g.
When you did the changes to the files, you can compress it as a zip again and make sure the extension is .jar

Hope that was somewhat helpful for you.

**Comment by bong0** [comment]
Hey @NuclearPowerNerd the META_INF directory and the listings are within a .jar file. A jar is basically a .zip and can be unpacked using a zip tool/extractor. 7zip should do e.g.
When you did the changes to the files, you can compress it as a zip again and make sure the extension is .jar

Hope that was somewhat helpful for you.

**Comment by NuclearPowerNerd** [comment]
> Hey [@NuclearPowerNerd](https://github.com/NuclearPowerNerd) the META_INF directory and the listings are within a .jar file. A jar is basically a .zip and can be unpacked using a zip tool/extractor. 7zip should do e.g. When you did the changes to the files, you can compress it as a zip again and make sure the extension is .jar
> 
> Hope that was somewhat helpful for you.

Thanks - though after I re-zip everything I get the error `Error: Invalid or corrupt jarfile MY/PATH/TeXidote/textidote_patched.jar`

To be clear, this is what I did.
 1. `unzip textidote.jar -d textidote_unzipped/`
 2. Edit the files under `META_INF` as indicated in @WrichikBasu response
 3. `tar -zcvf textidote_patched.jar textidote_unzipped/`

**Comment by sylvainhalle** [comment]
@NuclearPowerNerd The last command does not create a **zip** file. It creates a single **tar** file out of all the files in the folder, and compresses that single file with **gzip** (not the same thing as zip!), and gives it the .jar extension.

This should work:

```
7z a textidote_patched.zip textidote_unzipped/
mv textidote_patched.zip textidote_patched.jar
```

**Comment by NuclearPowerNerd** [comment]
> [@NuclearPowerNerd](https://github.com/NuclearPowerNerd) The last command does not create a **zip** file. It creates a single **tar** file out of all the files in the folder, and compresses that single file with **gzip** (not the same thing as zip!), and gives it the .jar extension.
> 
> This should work:
> 
> ```
> 7z a textidote_patched.zip textidote_unzipped/
> mv textidote_patched.zip textidote_patched.jar
> ```

Thanks, though I still get the error about invalid/corrupt jarfile.

**Comment by sylvainhalle** [comment]
Just to be sure: are you zipping from the folder that holds MANIFEST.MF, or from some parent folder? Java expect the folder with MANIFEST.MF to be the root of the archive.

**Comment by NuclearPowerNerd** [comment]
> Just to be sure: are you zipping from the folder that holds MANIFEST.MF, or from some parent folder? Java expect the folder with MANIFEST.MF to be the root of the archive.

I don't see that in the folder that I unzipped `texidote.jar` into. Is it supposed to be at the root level? Here is what I see.

```
LICENSE
META-INF/
README.md
about.html
at/
bert-lm.proto
ca/
ch/
cn/
com/
data/
de/
dumonts/
edu/
emojis.json
en-chunker.bin
en-pos-maxent.bin
en-token.bin
git.properties
gnu/
google/
io/
javax/
jetty-dir.css
junit/
languages/
languages.shorttext/
license.html
logback-test.xml
logback.xml
mariadb.properties
ml_server.proto
module-info.class
morfologik/
net/
opennlp/
org/
reactor/
rule-coverage.txt
spark/
tec/
tech/
testinput.txt
testrules.bat
testrules.sh
third-party-licenses/
```

**Comment by sylvainhalle** [comment]
My mistake, MANIFEST.MF is in the META-INF folder. From what I see, the file you have has the same top-level content as the one I create on my side. Will try to reproduce the steps and see what I can deduce from that.
