### ISSUE TITLE
Exception by empty section

### ISSUE THREAD

**Issue by gilbertf** [sylvainhalle/textidote#68]
A document with empty chapter can not be checked by textidote due to the following error:
Exception in thread "main" java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at ca.uqac.lif.textidote.rules.CheckSubsectionSize.evaluate(CheckSubsectionSize.java:102)
	at ca.uqac.lif.textidote.Linter.evaluateAll(Linter.java:149)
	at ca.uqac.lif.textidote.Main.mainLoop(Main.java:567)
	at ca.uqac.lif.textidote.Main.mainLoop(Main.java:124)
	at ca.uqac.lif.textidote.Main.main(Main.java:110)

**Comment by sylvainhalle** [comment]
Hi! Thanks for your feedback. Could you provide me a minimal TeX file that produces this error please?

**Comment by gilbertf** [comment]
Yep:
\documentclass[]{scrbook}
\usepackage{lmodern}
\begin{document}
\section{A}
\chapter{B}
\chapter{C}
\end{document}
