### ISSUE TITLE
MissingFormatWidthException: %0d

### ISSUE THREAD

**Issue by Novaal** [sylvainhalle/textidote#75]
Hi, 

i'm getting the follwoing error, when i'm running textidote inside of a docker container (Ubuntu 18.04, OpenJRE 8). When textidote runs inside of a virtual Machine (also Ubuntu 18.04, OpenJRE 8), i don't have this problem.

```bash
TeXtidote v0.7.1 - A linter for LaTeX documents and others
(C) 2018-2019 Sylvain Hall? - All rights reserved

Found 0 warning(s)
Total analysis time: 3 second(s)

Exception in thread "main" java.util.MissingFormatWidthException: %0d
	at java.util.Formatter$FormatSpecifier.checkNumeric(Formatter.java:3022)
	at java.util.Formatter$FormatSpecifier.checkInteger(Formatter.java:2982)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2729)
	at java.util.Formatter.parse(Formatter.java:2560)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at ca.uqac.lif.textidote.render.HtmlAdviceRenderer.printLineNumber(HtmlAdviceRenderer.java:258)
	at ca.uqac.lif.textidote.render.HtmlAdviceRenderer.render(HtmlAdviceRenderer.java:67)
	at ca.uqac.lif.textidote.Main.mainLoop(Main.java:601)
	at ca.uqac.lif.textidote.Main.mainLoop(Main.java:124)
	at ca.uqac.lif.textidote.Main.main(Main.java:110)
```
How can i fix it?

Thanks for any help.

**Comment by sylvainhalle** [comment]
Hi! Could you give me a minimal input file that exhibits this problem?

**Comment by Novaal** [comment]
I found the problem: I had german `Umlaute` in some comments.

To fix this issue, i had to set the correct locale in my docker image.
So i used the follwing commands when building the docker image.

```bash
apt-get install -y locales
sed -i -e 's/# de_DE.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/' /etc/locale.gen 
dpkg-reconfigure --frontend=noninteractive locales 
update-locale LANG=de_DE.UTF-8
```
Now everything works like expected.
