### ISSUE TITLE
LanguageTool does not recognise language code

### ISSUE THREAD

**Issue by roddhjav** [sylvainhalle/textidote#94]
Hi, thank for this tool, it is very useful.

I get a new error with textidote 0.8 installed from the deb file. When I run: 
`textidote --check en_UK <file>`

I get the following error:
```
TeXtidote v0.8 - A linter for LaTeX documents and others
(C) 2018-2019 Sylvain Hall? - All rights reserved

Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.languagetool.language.English.getRelevantRules(English.java:201)
	at org.languagetool.language.BritishEnglish.getRelevantRules(BritishEnglish.java:49)
	at org.languagetool.JLanguageTool.getAllBuiltinRules(JLanguageTool.java:390)
	at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:276)
	at org.languagetool.JLanguageTool.<init>(JLanguageTool.java:305)
	at org.languagetool.MultiThreadedJLanguageTool.<init>(MultiThreadedJLanguageTool.java:86)
	at org.languagetool.MultiThreadedJLanguageTool.<init>(MultiThreadedJLanguageTool.java:67)
	at org.languagetool.MultiThreadedJLanguageTool.<init>(MultiThreadedJLanguageTool.java:51)
	at ca.uqac.lif.textidote.rules.CheckLanguage.<init>(CheckLanguage.java:86)
	at ca.uqac.lif.textidote.Main.mainLoop(Main.java:584)
	at ca.uqac.lif.textidote.Main.mainLoop(Main.java:126)
	at ca.uqac.lif.textidote.Main.main(Main.java:112)
Caused by: java.lang.IllegalArgumentException: 'en' is not a language code known to LanguageTool. Supported language codes are: zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See http://wiki.languagetool.org/java-api for details.
	at org.languagetool.Languages.getLanguageForShortCode(Languages.java:237)
	at org.languagetool.Languages.getLanguageForShortCode(Languages.java:214)
	at org.languagetool.rules.en.EnglishDashRule.<clinit>(EnglishDashRule.java:37)
	... 12 more
```

It seems to be link [to this issue](https://forum.languagetool.org/t/languagetool-in-a-simple-java-application/236).

**Comment by sylvainhalle** [comment]
There was an error when I uploaded the files for the release; try downloading it again, this should be fixed.
